[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps = 
    h2zero/NimBLE-Arduino @ ^2.0.0
build_flags = 
    -DNIMBLE_DEBUG_DISABLED
    -DCORE_DEBUG_LEVEL=0 